INSERT INTO cliente (nome, telefone) VALUES
    ("Andréia Silva", "(27) 90001-0000"),
    ("Breno Costa", "(27) 90002-0001"),
    ("Camila Oliveira", "(27) 90003-0002"),
    ("Daniel Souza", "(27) 90004-0003"),
    ("Eduarda Martins", "(27) 90005-0004"),
    ("Felipe Almeida", "(27) 90006-0005"),
    ("Gabriela Lima", "(27) 90007-0006"),
    ("Henrique Pereira", "(27) 90008-0007"),
    ("Isadora Rocha", "(27) 90009-0008"),
    ("João Mendes", "(27) 90010-0009"),
    ("Karina Barbosa", "(27) 90011-0010"),
    ("Leandro Cardoso", "(27) 90012-0011"),
    ("Mariana Ribeiro", "(27) 90013-0012"),
    ("Natália Fernandes", "(27) 90014-0013"),
    ("Otávio Gomes", "(27) 90015-0014"),
    ("Priscila Dias", "(27) 90016-0015"),
    ("Quintino Moreira", "(27) 90017-0016"),
    ("Renata Castro", "(27) 90018-0017"),
    ("Samuel Teixeira", "(27) 90019-0018"),
    ("Thaís Santos", "(27) 90020-0019"),
    ("Ulisses Ferreira", "(27) 90021-0020"),
    ("Valéria Nogueira", "(27) 90022-0021"),
    ("William Ribeiro", "(27) 90023-0022"),
    ("Ximena Figueira", "(27) 90024-0023"),
    ("Yasmin Correia", "(27) 90025-0024"),
    ("Zeca Monteiro", "(27) 90026-0025"),
    ("Alice Pires", "(27) 90027-0026"),
    ("Bruno Guimarães", "(27) 90028-0027"),
    ("Cecília Araújo", "(27) 90029-0028"),
    ("Diego Castro", "(27) 90030-0029"),
    ("Esther Ramos", "(27) 90031-0030"),
    ("Fábio Barros", "(27) 90032-0031"),
    ("Giovanna Borges", "(27) 90033-0032"),
    ("Hugo Assis", "(27) 90034-0033"),
    ("Iara Leite", "(27) 90035-0034"),
    ("Jorge Diniz", "(27) 90036-0035"),
    ("Larissa Melo", "(27) 90037-0036"),
    ("Maurício Vieira", "(27) 90038-0037"),
    ("Nicole Ramos", "(27) 90039-0038"),
    ("Oscar Falcão", "(27) 90040-0039"),
    ("Paula Rezende", "(27) 90041-0040"),
    ("Rafael Monteiro", "(27) 90042-0041"),
    ("Sofia Cunha", "(27) 90043-0042"),
    ("Tiago Santana", "(27) 90044-0043"),
    ("Vitória Lacerda", "(27) 90045-0044"),
    ("Wagner Nunes", "(27) 90046-0045"),
    ("Xavier Pinheiro", "(27) 90047-0046"),
    ("Yuri Rocha", "(27) 90048-0047"),
    ("Zilda Albuquerque", "(27) 90049-0048"),
    ("Leonel Gomes", "(27) 90050-0049");
    
INSERT INTO endereco_cliente (id_cliente, logradouro, numero, bairro, cidade) VALUES
    (1,  "R. das Palmeiras",            "45",           "Jardim Vitória",         "Vitória"),
    (2,  "Av. Espírito Santo",           "115",          "Centro",                 "Vitória"),
    (3,  "R. São João Batista",          "1089",         "Vila Nova",              "Vitória"),
    (4,  "Av. da Vitória",               "134",          "Praia do Canto",         "Vitória"),
    (5,  "Rua das Acácias",              "220",          "Jardim da Penha",        "Vitória"),
    (6,  "Av. dos Trabalhadores",        "500",          "Centro",                 "Vila Velha"),
    (7,  "Rua das Orquídeas",            "230",          "Jardim Camburi",         "Vila Velha"),
    (8,  "Travessa São Geraldo",         "18 apto. 101", "Convento",               "Vila Velha"),
    (9,  "Rua dos Ipês",                 "44",           "Jardim Carioca",         "Vila Velha"),
    (10, "Av. dos Exilados",             "1150",         "Bairro do Porto",        "Vila Velha"),
    (11, "Rua das Mangueiras",           "68",           "Santa Isabel",           "Cariacica"),
    (12, "Av. Lucio Costa",              "142",          "Jardim Independência",   "Cariacica"),
    (13, "R. do Sol",                    "317",          "Jardim Santa Lúcia",     "Cariacica"),
    (14, "Av. das Oliveiras",            "764",          "Bosque",                 "Cariacica"),
    (15, "Rua Central",                  "51 apto. 3B",  "Jardim Boa Vista",       "Cariacica"),
    (16, "Av. dos Navegantes",           "980",          "Vila Nova",              "Cariacica"),
    (17, "Rua do Progresso",             "88",           "Centro",                 "Cariacica"),
    (18, "Travessa do Sol",              "55 apto. 5",   "Jardim Alvorada",        "Cariacica"),
    (19, "Av. dos Pescadores",           "220",          "Bairro das Flores",      "Cariacica"),
    (20, "Rua dos Ventos",               "330",          "Parque Residencial",     "Cariacica"),
    (21, "Av. Getúlio Vargas",           "501",          "Centro",                 "Serra"),
    (22, "R. das Gaivotas",              "99",           "Zona Sul",               "Serra"),
    (23, "Rua Encantada",                "142 apto. 12", "Jardim Primavera",       "Serra"),
    (24, "Av. dos Imigrantes",           "1375",         "Bairro Novo",            "Serra"),
    (25, "Rua Aurora",                   "59",           "Jardim Horizonte",       "Serra"),
    (26, "Av. das Américas",             "404",          "Centro",                 "Serra"),
    (27, "Rua dos Lírios",               "720",          "Residencial Sol",        "Serra"),
    (28, "Travessa da Alegria",          "26",           "Jardim Florido",         "Serra"),
    (29, "Av. Maringá",                  "800",          "Vila Bella",             "Serra"),
    (30, "Rua do Comércio",              "120",          "Jardim Universal",       "Serra"),
    (31, "Rua do Sossego",               "410",          "Jardim América",         "Santana"),
    (32, "Av. da Liberdade",             "88 apto. 7",   "Centro",                 "Santana"),
    (33, "R. dos Navegantes",            "12 apto. 202", "Jardim Atlântico",       "Santana"),
    (34, "Av. Beira Mar",                "910",          "Praia da Costa",         "Santana"),
    (35, "Rua dos Coqueiros",            "210",          "Bairro Tropical",        "Santana"),
    (36, "Travessa das Violetas",        "33",           "Jardim Bela Vista",      "Santana"),
    (37, "Av. dos Pioneiros",            "855",          "Centro",                 "Santana"),
    (38, "Rua das Mangueiras",           "68",           "Jardim dos Eucaliptos",   "Santana"),
    (39, "R. dos Imigrantes",            "340",          "Vila Industrial",        "Santana"),
    (40, "Av. do Progresso",             "220",          "Bairro Verde",           "Santana"),
    (41, "Rua São Francisco",            "147",          "Centro",                 "Linhares"),
    (42, "Av. do Contorno",              "320",          "Jardim Esperança",       "Linhares"),
    (43, "Travessa das Acácias",         "58 apto. 2A",  "Jardim Tropical",        "Linhares"),
    (44, "R. dos Cedros",                "210",          "Bairro Novo",            "Linhares"),
    (45, "Av. Itapuã",                   "890",          "Jardim Piratininga",     "Linhares"),
    (46, "Av. Costa do Sol",             "100",          "Centro",                 "Guarapari"),
    (47, "Rua das Conchas",              "600",          "Jardim Oceânico",        "Guarapari"),
    (48, "R. do Areal",                  "350 apto. 4",  "Bairro dos Pescadores",  "Guarapari"),
    (49, "Travessa do Mar",              "220",          "Recanto das Águas",      "Guarapari"),
    (50, "Av. do Sol Nascente",          "500",          "Vila dos Coqueiros",     "Guarapari");
    

INSERT INTO pet (id_cliente, id_especie, nome, raca, porte, cor, sexo, e_castrado, comportamento ) VALUES
    (1, 1, "Fred", "Shi-tzu", "P", "Branco e marrom", "M", "N", "Agitado"),
    (2, 2, "Mika", "Siamês", "M", "Branco e cinza", "F", "S", "Dócil"),
    (3, 1, "Caramelo", "Vira-lata", "M", "Caramelo", "M", "N", "Dócil"),
    (4, 2, "Luna", "Persa", "P", "Cinza", "F", "S", "Calma"),
    (5, 1, "Thor", "Pastor Alemão", "G", "Preto e marrom", "M", "S", "Ativo"),
    (6, 2, "Bella", "Siamês", "M", "Branco", "F", "N", "Brincalhona"),
    (7, 1, "Rex", "Bulldog", "M", "Branco e amarelado", "M", "S", "Protector"),
    (8, 2, "Simba", "Siberiano", "G", "Cinzento", "M", "N", "Curioso"),
    (9, 1, "Max", "Labrador", "G", "Amarelo", "M", "S", "Dócil"),
    (10, 2, "Nina", "Maine Coon", "M", "Ruivo", "F", "S", "Alegre"),
    (11, 1, "Buddy", "Golden Retriever", "G", "Dourado", "M", "S", "Amigável"),
    (12, 2, "Molly", "Ragdoll", "P", "Branco e cinza", "F", "N", "Calma"),
    (13, 1, "Zeus", "Dálmata", "M", "Branco com manchas", "M", "S", "Ativo"),
    (14, 2, "Lili", "Bengal", "M", "Laranja e marrom", "F", "S", "Curiosa"),
    (15, 1, "Oscar", "Boxer", "G", "Tostado", "M", "N", "Protetor"),
    (16, 2, "Cleo", "Siamês", "P", "Cinza e branco", "F", "S", "Brincalhona"),
    (17, 1, "Sam", "Vira-lata", "M", "Caramelo", "M", "N", "Dócil"),
    (18, 2, "Daisy", "Persa", "M", "Branca", "F", "S", "Tranquila"),
    (19, 1, "Ben", "Poodle", "P", "Branco", "M", "S", "Sapeca"),
    (20, 2, "Lola", "Sphynx", "M", "Rosa", "F", "N", "Curiosa"),
    (21, 1, "Charlie", "Bulldog Francês", "M", "Marrom", "M", "S", "Calmo"),
    (22, 2, "Nala", "Maine Coon", "G", "Ruivo", "F", "S", "Alegre"),
    (23, 1, "Rocky", "Pit Bull", "G", "Cinza", "M", "N", "Ativo"),
    (24, 2, "Mia", "Burmês", "P", "Preto", "F", "S", "Dócil"),
    (25, 1, "Bobby", "Labrador", "G", "Amarelo", "M", "S", "Amigável"),
    (26, 2, "Sassy", "Siamês", "P", "Branco e marrom", "F", "N", "Agitada"),
    (27, 1, "Jack", "Pastor Australiano", "M", "Caramelo", "M", "S", "Ativo"),
    (28, 2, "Kitty", "Persa", "P", "Cinza", "F", "S", "Calma"),
    (29, 1, "Duke", "Doberman", "G", "Preto", "M", "N", "Protetor"),
    (30, 2, "Zara", "Bengal", "M", "Laranja", "F", "S", "Curiosa"),
    (31, 1, "Leo", "Golden Retriever", "G", "Dourado", "M", "S", "Amigável"),
    (32, 2, "Olivia", "Ragdoll", "M", "Branco com cinza", "F", "N", "Tranquila"),
    (33, 1, "Apollo", "Pastor Alemão", "G", "Preto e marrom", "M", "S", "Ativo"),
    (34, 2, "Chloe", "Siberiano", "P", "Cinzento", "F", "S", "Dócil"),
    (35, 1, "Toby", "Labrador", "G", "Amarelo", "M", "N", "Sapeca"),
    (36, 2, "Lily", "Maine Coon", "M", "Ruivo", "F", "S", "Alegre"),
    (37, 1, "Bruno", "Boxer", "G", "Tostado", "M", "S", "Protetor"),
    (38, 2, "Sophie", "Burmês", "P", "Branca", "F", "N", "Calma"),
    (39, 1, "Atlas", "Dálmata", "M", "Branco com manchas", "M", "S", "Ativo"),
    (40, 2, "Pipa", "Sphynx", "P", "Rosa", "F", "S", "Brincalhona"),
    (41, 1, "Jasper", "Poodle", "P", "Branco", "M", "S", "Sapeca"),
    (42, 2, "Mimi", "Persa", "M", "Cinza", "F", "N", "Tranquila"),
    (43, 1, "Hunter", "Pit Bull", "G", "Cinza", "M", "S", "Ativo"),
    (44, 2, "Gala", "Bengal", "M", "Laranja e marrom", "F", "S", "Curiosa"),
    (45, 1, "Ace", "Doberman", "G", "Preto", "M", "N", "Protetor"),
    (46, 2, "Ruby", "Ragdoll", "P", "Branco e cinza", "F", "S", "Dócil"),
    (47, 1, "Simba", "Golden Retriever", "G", "Dourado", "M", "S", "Amigável"),
    (48, 2, "Kiki", "Maine Coon", "M", "Ruivo", "F", "N", "Alegre"),
    (49, 1, "Lucky", "Labrador", "G", "Amarelo", "M", "S", "Brincalhão"),
    (50, 2, "Zoe", "Siamês", "P", "Branco", "F", "S", "Curiosa"),
    (1, 1, 'Rex', 'Labrador', 'G', 'Dourado', 'M', 'S', 'Amigável'),
    (1, 1, 'Luna', 'Poodle', 'P', 'Branco', 'F', 'S', 'Brincalhona'),
    (1, 2, 'Mimi', 'Siamês', 'M', 'Cinza', 'F', 'N', 'Independente'),
    (3, 1, 'Thor', 'Rottweiler', 'G', 'Preto e marrom', 'M', 'S', 'Protetor'),
    (3, 2, 'Nina', 'Persa', 'P', 'Branco', 'F', 'S', 'Calma'),
    (5, 1, 'Bolt', 'Vira-lata', 'M', 'Caramelo', 'M', 'N', 'Energético'),
    (7, 2, 'Felix', 'Sphynx', 'M', 'Rosado', 'M', 'S', 'Curioso'),
    (7, 1, 'Mel', 'Golden Retriever', 'G', 'Dourado', 'F', 'S', 'Dócil'),
    (10, 2, 'Loki', 'Maine Coon', 'G', 'Rajado', 'M', 'N', 'Brincalhão'),
    (12, 1, 'Bella', 'Bulldog Francês', 'P', 'Tigrado', 'F', 'S', 'Apegada'),
    (12, 2, 'Oliver', 'Angorá', 'M', 'Branco', 'M', 'N', 'Independente'),
    (12, 1, 'Zoe', 'Shih Tzu', 'P', 'Preto e branco', 'F', 'S', 'Calma'),
    (15, 1, 'Rocky', 'Pastor Alemão', 'G', 'Preto', 'M', 'S', 'Obediente'),
    (18, 2, 'Luna', 'Ragdoll', 'M', 'Azul', 'F', 'S', 'Relaxada'),
    (18, 1, 'Max', 'Beagle', 'M', 'Tricolor', 'M', 'N', 'Farejador'),
    (20, 2, 'Charlie', 'British Shorthair', 'M', 'Cinza', 'M', 'S', 'Tranquilo'),
    (22, 1, 'Duke', 'Doberman', 'G', 'Preto e castanho', 'M', 'S', 'Vigilante'),
    (25, 1, 'Molly', 'Dachshund', 'P', 'Vermelho', 'F', 'S', 'Teimosa'),
    (25, 2, 'Simba', 'Bengal', 'M', 'Rajado', 'M', 'N', 'Ativo'),
    (28, 2, 'Chloe', 'Scottish Fold', 'P', 'Cinza', 'F', 'S', 'Carinhosa'),
    (30, 1, 'Toby', 'Boxer', 'M', 'Tigrado', 'M', 'N', 'Brincalhão'),
    (30, 1, 'Lola', 'Pug', 'P', 'Abricot', 'F', 'S', 'Alegre'),
    (30, 2, 'Milo', 'Siberiano', 'M', 'Branco', 'M', 'N', 'Aventureiro'),
    (33, 2, 'Sophie', 'Exótico', 'P', 'Marrom', 'F', 'S', 'Tímida'),
    (35, 1, 'Buddy', 'Husky Siberiano', 'G', 'Preto e branco', 'M', 'S', 'Independente'),
    (35, 2, 'Lily', 'Sphynx', 'M', 'Branco', 'F', 'N', 'Extrovertida'),
    (38, 1, 'Cooper', 'Cocker Spaniel', 'M', 'Dourado', 'M', 'S', 'Amável'),
    (40, 2, 'Gizmo', 'Devon Rex', 'P', 'Cinza', 'M', 'N', 'Brincalhão'),
    (42, 1, 'Bailey', 'Border Collie', 'M', 'Preto e branco', 'F', 'S', 'Inteligente'),
    (42, 2, 'Cleo', 'Abissínio', 'P', 'Vermelho', 'F', 'N', 'Ativa'),
    (45, 1, 'Bear', 'São Bernardo', 'G', 'Marrom e branco', 'M', 'S', 'Calmo'),
    (47, 2, 'Pepper', 'Cornish Rex', 'P', 'Preto', 'F', 'S', 'Curiosa'),
    (47, 1, 'Daisy', 'Yorkshire Terrier', 'P', 'Cinza e dourado', 'F', 'N', 'Energética'),
    (50, 2, 'Jack', 'Norueguês da Floresta', 'G', 'Rajado', 'M', 'S', 'Gentil');

